{{ config(materialized='table') }}

select
 DATE_KEY as DATE_SK  
,DATE_KEY
,DATE_YMD
,FULL_DATE
,DATE_STR
,YEAR
,MONTH
,MONTH_ABBR
,MONTH_NAME
,DAY_OF_WEEK
,DAY_OF_MONTH_NUMBER
,DAY_OF_MONTH_W_ZEROS
,DAY_OF_YEAR
,WEEK_OF_YEAR
,MONTH_NUMBER
,YEAR_NUMBER
,QUARTER_NUMBER
,QUARTER_NAME
,DAY_ABBR
,FIRST_DAY_OF_MONTH
,LAST_DAY_OF_MONTH
,FIRST_DAY_OF_QUARTER
,LAST_DAY_OF_QUARTER
,FIRST_DAY_OF_YEAR
,LAST_DAY_OF_YEAR
,IS_WEEKEND
,IS_SATURDAY
,IS_SUNDAY
,IS_HOLIDAY
,YEAR_MONTH
,YEAR_QUARTER
,YEAR_FOUR_DIGITS
,YEAR_LAST_TWO_DIGITS
,CREATED_AT

from {{ ref('buv_calendar') }}